### ISSUE TITLE
Apt repository signing errors on Ubuntu 22.04 arm64 and 24.04 x86_64 

### ISSUE THREAD

**Issue by julian45** [adoptium/installer#1066]
On Ubuntu with the versions and architectures listed in the title, apt reports signing errors upon `apt update`:

<img width="865" alt="2024-12-02_19-48-28" src="https://github.com/user-attachments/assets/5e19d7a5-c833-4b47-ba14-1d2349968f2d">

<img width="865" alt="2024-12-02_19-48-54" src="https://github.com/user-attachments/assets/8385e773-28b9-4cc6-94a1-c5623c57727b">

The 22.04 server has had the repository installed for some time and is only now throwing errors; on the other hand, the 24.04
installation never had the adoptium repos before this evening, and the repo was installed following the directions provided [here](https://adoptium.net/installation/linux/).

**Comment by DekusDenial** [comment]
same

**Comment by karianna** [comment]
@julian45 Can you try again now?  Just checking to see if this is a persistent issue.

**Comment by loviji** [comment]
> @julian45 Can you try again now? Just checking to see if this is a persistent issue.

it's persistent for my WSL (Ubuntu 22.04.5 LTS).

**Comment by SCHUMANN-Otto** [comment]
Same here for debian bookworm!
![grafik](https://github.com/user-attachments/assets/75487837-480f-4dc3-9e50-40a229d8d466)

**Comment by NguyHa03** [comment]
I see it is back to normal now

**Comment by MoinMojn** [comment]
I had the same issue earlier today on a Debian bookworm machine.
During that time i've tried to access the artifactory instance via the JFrog web UI but most of the HTTP request returned 503 Service Unavailable HTTP errors. The error message indicated some "backend unhealthy" error messages, unfortunately I did not take note of the exact message.

The issue seems to be resolved by now, both the debian repository and Artifactory web UI are working again.

**Comment by karianna** [comment]
Yep we applied a fix behind the scenes, thanks all!
