### ISSUE TITLE
Create autoupdater for AdoptOpenJDK binaries

### ISSUE THREAD

**Issue by tellison** [adoptium/installer#4]
BitRock installers include [an auto-update tool](https://installbuilder.bitrock.com/docs/installbuilder-userguide/ar01s23.html).

This issue is to investigate whether the auto-updater is suitable for the project, and write the client and server metadata to represent our releases.

A quick read through the docs implies that the autoupdater has to be invoked by cron / task scheduler on a regular check for updates on some platforms.

**Comment by alexhass** [comment]
If we think about Windows we need to keep in mind that users are typically not administrators and are not allowed to install software. Automatic update need to be an optional _feature_ that could be enabled by default. Not difficult, just do not forget about this, please.

**Comment by maverick74** [comment]
Is there anything new in this front?

Would be great to have this for Windows!!!

**Comment by karianna** [comment]
This work still needs to be scheduled in.

**Comment by gjabouley-invn** [comment]
Could it be possible to start small and just do a regular check for updates?
Even if it then redirect to download link, at least users would be notified of availability of an update. Something like CCleaner update check for example (i think it is implemented using a scheduled task)

**Comment by robmosys** [comment]
One thing to note is that a web API is already available to query for versions of the openjdk:
https://github.com/AdoptOpenJDK/openjdk-api-v3
So, what is required is tool to:
1. Periodically query the API
2. Compare results against installed jdks.
3. Notify user of status, and handle responses.
4. Download & install API.
5. Handle failures in a responsible manner.
It's always possible to start with a tool that gets to stage 3, dispatching user to download page to get updated software, before doing 4 and 5.

**Comment by jlgager24** [comment]
I am currently in the process of writing an updater. Not sure how long it will take because I work full time but I hope to have some sort of beta made soon. I am looking to write it in java8 so it is usable for all versions and and I am using Jackson for the json parser. I am also currently using the github releases api to try to get the download links but I can use the AdoptOpenJDK api if everyone thinks thats better or I can do both if so desired. If anyone has any ideas for things to add that havent been mentioned or any suggestions at all please let me know.

**Comment by maverick74** [comment]
Happy 2020.

@jlgager24 any update to share with the rest of us? :)

**Comment by jlgager24** [comment]
Hey everyone sorry I haven't posted an update in a while. I was very sick over the holidays and haven't been able to put in as much time as I have wished. My plan is to have something to show you guys by the end of February. Thanks for being patient.

**Comment by maverick74** [comment]
No hurry. Health (and family) are always first. Hope you're OK already.

**Comment by jlgager24** [comment]
I am doing much better now thanks.

**Comment by maverick74** [comment]
any news?

**Comment by Suyashtnt** [comment]
any news? I would really like this

**Comment by aahlenst** [comment]
Sorry, there are no news in that area. I don't want us to get into the business of developing and maintaining an auto updater which is a complex undertaking. I especially dread the support requests caused by the auto updater. Using an existing auto updater would most likely require us to switch from WiX to https://www.installaware.com/ or https://installbuilder.com/ which have solved that problem. That would be a lot of work, too. OSS solutions like Sparkle aren't a drop-in solution, either.

If anyone wants to help or fund development, please get in touch.

**Comment by maverick74** [comment]
@aahlenst it could, at the very least, notify users when there is a new version available.

I think that much is pretty easy to implement, ain't it?

**Comment by aahlenst** [comment]
@maverick74 If it was easy, I guess someone would have done it by now.

If you want to inform people when running `java`, you had to patch that into the `java` executable. We would have to consistently apply that patch on top of the regular OpenJDK/OpenJ9 changes. So that would be a consistent source of work apart from the fact that there are other executables. How would we deal with jlink'ed binaries? jpackage? Oh my.

The other option is a scheduled task. But what is if you want to keep the specific version? What if there are multiple versions/users? What if it's a per-user install? What if somebody wants to mute it until next boot/next week/next version?

**Comment by maettle** [comment]
> 
> 
> @maverick74 If it was easy, I guess someone would have done it by now.

> 
> The other option is a scheduled task. But what is if you want to keep the specific version? What if there are multiple versions/users? What if it's a per-user install? What if somebody wants to mute it until next boot/next week/next version?

Apologies if I did understand something wrong, but the minor releases are always bug-/securityfixes, aren't they? So you just don't have a reason to NOT want the newest version. But if you must keep an old version and want to mute it: why don't remember that choice in a file/variable/etc? 
If its a per user install: there are per-user tasks. 
Multiple versions: multiple (per user) tasks.

I really don't see a problem with managing your concerns. I would've written my own scheduled task, but I don't know what/which url I should query...

**Comment by aahlenst** [comment]
@maettle Those are requirements, not insurmountable obstacles. You asked for an URL, there you go: https://api.adoptopenjdk.net/. I‘d be very happy if you can put something together that works well and is easy to maintain. If you have questions, https://adoptopenjdk.net/slack.html, there is a channel called *installer*. I take Java or C#.

Further requirements:
* Windows 8.1 and up
*Windows Server 2012 R2 and up
* Yell at people if they use a version that has reached its EOL.

**Comment by tushev** [comment]
Hello guys,

If you want something to be done, do it yourself. Thinking like that (and needing the updater) I created such a tool and I want to share it with you.

![update_dialog](https://user-images.githubusercontent.com/18406797/82139110-191e5000-983f-11ea-9cdb-0aacfe83bcb1.png)
![config_dialog](https://user-images.githubusercontent.com/18406797/82139125-305d3d80-983f-11ea-8a51-8deb98a12566.png)

It is available at https://github.com/tushev/aojdk-updatewatcher

Its principles and philosophy are well described in Readme.

Ironically, this tool is written in C# + WPF, because I am not a Java developer. I just need the tool for myself because some software I use requires Java. If you find it useful for you too, I will be glad :)

**Comment by Suyashtnt** [comment]
> Hello guys,
> 
> If you want something to be done, do it yourself. Thinking like that (and needing the updater) I created such a tool and I want to share it with you.
> 
> ![update_dialog](https://user-images.githubusercontent.com/18406797/82139110-191e5000-983f-11ea-9cdb-0aacfe83bcb1.png)
> ![config_dialog](https://user-images.githubusercontent.com/18406797/82139125-305d3d80-983f-11ea-8a51-8deb98a12566.png)
> 
> It is available at [tushev/aojdk-updatewatcher](https://github.com/tushev/aojdk-updatewatcher)
> 
> Its principles and philosophy are well described in Readme.
> 
> Ironically, this tool is written in C# + WPF, because I am not a Java developer. I just need the tool for myself because some software I use requires Java. If you find it useful for you too, I will be glad :)

You are an absolut legend, thanks

**Comment by aahlenst** [comment]
@tushev Do I understand correctly that the tool cannot cope with multiple versions of AdoptOpenJDK being installed on the same machine? Or the other way around: It only updates the JDK at `JAVA_HOME`?

**Comment by tushev** [comment]
@aahlenst It's designed primarily as an end-user thing: in most 'everyday' cases there is just one single installation of JRE,not even JDK :). As for JAVA_HOME - you can choose **either** JAVA_HOME or a specific other path. 

If you need to check multiple JDKs, currently you can create a very simple batch script that will rotate **user.config** files and run this tool several times (I expect that different MSIs will update them correctly to different directories). Or maybe I will add such functionality in some future release.

**Comment by karianna** [comment]
@tushev Thanks for your willingness to contribute to AdoptOpenJDK!  This is what OSS is all about :-).  I've added it to the TSC agenda to review and then discuss with you further (will be the end of the week)

**Comment by maverick74** [comment]
@tushev this is amazing!!! Thank you!!!

It would be great to have this "integrated" with AdoptOpenJDK installation!

I still have a question, however: if i have OpenJDK v.10 and OpenJDK v.11 gets out will i also get notified? 
Or does it notify me only on minor releases ( OpenJDK v.10.1 -> OpenJDK v.10.2 )?

**Comment by tushev** [comment]
@maverick74 In current version, you set the release (like **10**, 11) in my GUI and the updater then routinely checks API that looks like `/v3/assets/latest/10/hotspot`. If that API will tell `no new versions for 10`, you won't get any new notifications and probably you will have to switch manually (AFAIK, this is what happening now). 

If the API will tell something like `no new versions for 10, EOL reached: true, recommended new branch: 11` then I will add corresponding functionality to the app (sure no automatic updates, informed consent to switching to another branch required). This is to be suggested and discussed with AdoptOpenJDK TSC.

> It would be great to have this "integrated" with AdoptOpenJDK installation!

I think it's possible to create some kind of 'configuration' (like release number and installation path) that will be provided by AdoptOpenJDK MSI installer, so when you install AdoptOpenJDK, the updater begins using this provided configuration and don't asks user for anything. As @karianna wrote, this is to be discussed as well.

I think I can add support for multiple configurations, both user-configured and provided by installers.

**Comment by maverick74** [comment]
> @maverick74 In current version, you set the release (like **10**, 11) in my GUI and the updater then routinely checks API that looks like `/v3/assets/latest/10/hotspot`. If that API will tell `no new versions for 10`, you won't get any new notifications and probably you will have to switch manually (AFAIK, this is what happening now).

Suggestion: Would be good to have an option to always keep up with the latest release (without having to choose it manually)


> > It would be great to have this "integrated" with AdoptOpenJDK installation!
> 
> I think it's possible to create some kind of 'configuration' (like release number and installation path) that will be provided by AdoptOpenJDK MSI installer, so when you install AdoptOpenJDK, the updater begins using this provided configuration and don't asks user for anything. As @karianna wrote, this is to be discussed as well.

Yes, but what i meant to say was that it would be good if the AdoptOpenJDK installer would also offer the option to automatically install your updater as an extra feature for those who might want that function

**Comment by aahlenst** [comment]
We're happy to bundle it with the AdoptOpenJDK MSIs. The minimum bar to clear here:

* Apache License 2.0
* Automated tests
* Works with multiple AdoptOpenJDK installations
* Removal of all mentions of OpenJDK, Java and similar terms that are copyrighted by Oracle as well as all related artwork.

This does not mean that you have to do everything on your own (except the licensing).

**Comment by OrangeDog** [comment]
> all mentions of OpenJDK, Java and similar terms that are copyrighted by Oracle

Pretty sure you mean trademark, not copyright.
And AdoptOpenJDK is fine?

By [the guidelines](https://www.oracle.com/legal/trademarks.html) you can use phrases like "OpenJDK update check", but calling your own product AdoptOpenJDK is disallowed (assuming "OpenJDK" is actually an Oracle trademark).

**Comment by aahlenst** [comment]
> Pretty sure you mean trademark, not copyright.

👍 

> By the guidelines you can use phrases like "OpenJDK update check", but calling your own product AdoptOpenJDK is disallowed (assuming "OpenJDK" is actually an Oracle trademark).

@karianna is the expert in this area. Generally speaking, we should strive to stay away from anything that is a TM/R of Oracle or could be potentially misleading. "OpenJDK update check" could be considered to be misleading (it's AdoptOpenJDK, you cannot obtain an OpenJDK MSI), and a non-starter if OpenJ9 can be obtained through it because OpenJ9 is not OpenJDK (Oracle's stance).

**Comment by OrangeDog** [comment]
I used "OpenJDK" because that was you're example, and I'm not sure whether it is actually a trademark. "Java" definitely is, but you're still allowed to say "Java update check", or "current Java version" etc. which you said have to be removed.

If "OpenJDK" is a trademark, it's pretty clear you're not allowed to call yourself AdoptOpenJDK.
> Do not use Oracle trademarks or potentially confusing variations as all or part of your company, product or service names.

**Comment by karianna** [comment]
> I used "OpenJDK" because that was you're example, and I'm not sure whether it is actually a trademark. "Java" definitely is, but you're still allowed to say "Java update check", or "current Java version" etc. which you said have to be removed.
> 
> If "OpenJDK" is a trademark, it's pretty clear you're not allowed to call yourself AdoptOpenJDK.
> 
> > Do not use Oracle trademarks or potentially confusing variations as all or part of your company, product or service names.

We're working on a rename.

**Comment by aahlenst** [comment]
While we appreciate the work that was done and see the usefulness in the proposed updater, we are not ready to take the responsibility on, even less to incorporate it into our MSIs. We want to leave it to the community to develop it further. This is not a definitive rejection. We plan to reconsider it.

We are also receptive to alternative proposals, especially if they are already battle tested, well maintained and OSS or part of Windows itself. Using a proprietary software (like Bitrock) is not something we want to persue because it makes life difficult for contributors.

**Comment by tushev** [comment]
I think that maybe I will add support for multiple versions in the future (as it seems to be a handy feature).

In the meantime I changed the artwork so it uses AdoptOpenJDK brand now. Hope you don't mind it :)

**Comment by douph1** [comment]
@karianna , so `We're working on a rename.` was not a joke !

**Comment by karianna** [comment]
> @karianna , so `We're working on a rename.` was not a joke !

It was not.  We wanted to be respectful of trademarks and the move to the Eclipse Foundation was the right time to make that change.

**Comment by jlgager24** [comment]
Hey everyone, again I apologize for no progress on this yet. A lot has been going on for me this year with family and health issues and wasn't able to put a lot of time on this.  That being said I have been working on an updater written in java 8 that will be console-based. I was looking to make a basic GUI using JavaFX but the java 8 OpenJDK does not have JavaFX included and there is no way to include it. I am still working out some small bugs with accessing the API and I hope to have a beta available within the next 2 weeks, If everyone feels it is needed then I am willing to make a GUI for it for java 11, the earliest LTS after java 8. I do not know Java Swing so if a GUI is needed for java 8 someone will need to make that. Also currently I am building this using the GitHub API so it is a little more involved due to the amount of info the API returns.

**Comment by douph1** [comment]
Hi @jlgager24 and thanks for this good news.
I think a console based java8 is good so many contributor can help/enhance the updater.
We can maybe also build it as a native exe with GraalVm :)
If we bundle it with the installer we probably don't need a visual tool to configure something as
we already know the install path, the jvm type(hotspot/openj9), the product category(jre/jdk) and the branch version number(8/11..)
Also we don't need a self-updater as it can be updated by installing a new JDK(msi)

**Comment by jlgager24** [comment]
@douph1 Thanks for your input! I will be looking into using GrailVM it looks like it should work. Also yes a GUI is not really necessary and the updater will accept different args to allow full control of how the app works. Also, I already have code completed that allows the download and install of the installer.

Everyone I am almost done and I will be finalizing and releasing a beta this weekend. I'm excited for everyone to see the code! I am going to try to comment the code and refactor as best as I can but that can be improved over time but it should be bug-free and will have the basic features completed.

**Comment by jlgager24** [comment]
I have finished the beta and the code is now available at https://github.com/JGCompTech/JUpdate-AdoptOpenJDKUpdater

I have packaged it as a jar and an exe file.

If anyone has any questions feel free to ask and also please feel free to post any pull requests or issues.

Thanks for being patient with me and I hope this helps everyone!

**Comment by tushev** [comment]
I've decided to refresh my C# skills (and finally learn MVVM pattern :). As a learning project, I've chosen my Update Watcher, and I would like to present to anyone who's interested in GUI tool - version 2:

![update_dialog](https://user-images.githubusercontent.com/18406797/94337871-3510da00-0007-11eb-8fbd-036ef67187b6.gif)
![config_dialog](https://user-images.githubusercontent.com/18406797/94337992-31318780-0008-11eb-90b9-6f3297f67fba.png)


Some new features:
* Support for multiple AdoptOpenJDK installations
* Automatic discovery of installations via Windows Registry
* Redesigned UI/UX
* App warns if `N` last _consecutive_ background update checks were unsuccessful (default `N=10`)
* Limited support for Most recent/ Most recent LTS options
* Other improvements, perfomance optimisations etc.

https://github.com/tushev/aojdk-updatewatcher

**Comment by mziehm** [comment]
Both Version 1.0.0 and 2.0.0 of the aojdk-updatewatcher from tushev are currently classified by multiple anti-virus software as malicious
V1.0.0: https://www.virustotal.com/gui/file/a9c71e8080066da9d31126ff4643ecee0ed08ba3ee6e0bf8c21013911c60a6a6/detection
V2.0.0: https://www.virustotal.com/gui/file/25662cec109284f2d702c58531d88002fd6c7c7515f911b8e1d04f73b1ba6edb/detection

I can't comment on whether there is reason for true concern. At the very least it is important to know and a practical limitation to being officially adopted or deployed on certain systems.

While the software from jlgager24/JGCompTech
https://www.virustotal.com/gui/file/89d3881f3340593674be295047409f7e2ed7d78c2a5fad885ae26a62332891a2/detection
does not have such classifications.

**Comment by tushev** [comment]
@mziehm , this is a [false positive](https://support.virustotal.com/hc/en-us/articles/115002121185-I-am-experiencing-a-false-positive-my-file-or-site-should-not-be-detected-). It usually happens with 'new' and 'unpopular' software (my humble 200+ downloads as of today definitely do not make it a world-class hit) - some engines just treat everything 'not popular' as threats.

Frankly, I've never heard before of those 4 antivirus engines. If there was something really malicious, the trustworthy ones AV would definitely show it.

The difference between jlgager24's one and my updaters is that I use Inno Setup for installer (that downloads .NET if necessary - this is really a very suspicious feature xD), while Joshua's updater is a 'run-now' command line tool. If you upload my main executable directly, it will give you [clean status as well](https://www.virustotal.com/gui/file/e03adf1a2d78ceac319132351201dcadf48079fb2027a83aa7c6864c36758a5a/detection).


If you are concerned about security, you can always clone the code and compile it yourself.

**Comment by douph1** [comment]
Extracting exe with https://constexpr.org/innoextract/ 
give me for the old 1.0.01 :
./AdoptOpenJDK-UpdateWatcher-1.0.0.0-setup.exe ->
7b4d8ff0c0adc168da4e15ee26812fe5f0cbd273bfebdef61b628f167b11d0f9  ./app/AdoptOpenJDK-UpdateWatcher.exe
274ko file with a create date in the future :) Creation Time	2103-01-09 20:12:43
https://www.virustotal.com/gui/file/7b4d8ff0c0adc168da4e15ee26812fe5f0cbd273bfebdef61b628f167b11d0f9/detection
only one "Malicious" from SecureAge APEX. @tushev 

and the new one : AJUpdateWatcher-2.0.0.0-setup.exe
e03adf1a2d78ceac319132351201dcadf48079fb2027a83aa7c6864c36758a5a  ./app/AJUpdateWatcher.exe
Creation Time	2071-04-26 06:09:31
https://www.virustotal.com/gui/file/e03adf1a2d78ceac319132351201dcadf48079fb2027a83aa7c6864c36758a5a/details
without warning
>No engines detected this file

**Comment by douph1** [comment]
and innosetup-6.0.5.exe himself is suspicious for SecureAge APEX https://www.virustotal.com/gui/file/ae6823b523df87e9441789e51845434e4e0e70aac0b88afe80f94f20f4b98acb/detection

**Comment by tushev** [comment]
@douph1 the dates look weird, but I cannot say why. Maybe it's an issue with Inno itself or innoextractor.

Checked my machine, the actual compilation dates are:
* for v1 (`7B4D8FF0C0ADC168DA4E15EE26812FE5F0CBD273BFEBDEF61B628F167B11D0F9`) actual date is 18.06.2020 17:55 UTC
* for v2 (`E03ADF1A2D78CEAC319132351201DCADF48079FB2027A83AA7C6864C36758A5A`) actual date is 26.09.2020 08:57 UTC

If I install the V2 package, `C:\Program Files\AJUpdateWatcher\AJUpdateWatcher.exe` has correct 'Modified' date (26.09.2020 08:57 UTC).

As of SecureAge APEX, I've heard that it has lots of FP reported, like this [one](https://www.reddit.com/r/antivirus/comments/et0h4p/secureage_apex_is_fp_or_i_have_problems/).

As of binaries, I use third-party stuff like Inno Setup with plugins, libs like DotNetProjects.Extended.Wpf.Toolkit etc. So I cannot be 100% sure about them, but they are generally respected by the community. I checked the DLLs, they all look clean by VT. Only the uninstaller - `unins000.exe`, generated by Inno setup, is [suspicious to one engine](https://www.virustotal.com/gui/file/8cceb45c03a56d14cffbde5cf15ea5a89301cd2fc9e0324b6b8d5c5ad0dd804d/detection).

Also I cannot be 100% sure that there is no super-duper alien worm that dwelled for years in my machine, bypassed all local AV checks and my own InfoSec principles, just to inject itself when I will compile `AJUpdateWatcher.exe` :) (only 99.99999% percent sure).

**But what I can say for 100% sure that I have no intention to create or distribute malicious code :)**

**Comment by alexhass** [comment]
Setups schould be Wix toolkit (MSI) based only.

Code signing the files schould stop virus detection. I think this is the only really safe way.

**Comment by mziehm** [comment]
@tushev @douph1 Thanks for investigating and providing an innosetup/installer free version.

**Comment by douph1** [comment]
Hi @tushev  @jlgager24  can you confirm that your updater see the last version :       "openjdk_version": "11.0.9.1+1", "semver": "11.0.9+101" ?

because the last is newer than the first :

    {
      "build": 11,
      "major": 11,
      "minor": 0,
      "openjdk_version": "11.0.9+11",
      "security": 9,
      "semver": "11.0.9+11"
    },
    {
      "build": 1,
      "major": 11,
      "minor": 0,
      "openjdk_version": "11.0.9.1+1",
      "security": 9,
      "semver": "11.0.9+101"
    },

**Comment by tushev** [comment]
@douph1 

**If we are speaking about API**, it seems that `"openjdk_version": "11.0.9.1+1", "semver": "11.0.9+101"` it is not present (at the time of writing this comment) in `https://api.adoptopenjdk.net/v3/assets/latest/11/hotspot`. I obtained the JSON both via https://api.adoptopenjdk.net/swagger-ui/#/Assets/get_v3_assets_latest__feature_version___jvm_impl_ and via debugging of my app. Both JSONs do not contain that version.

> Concerning API logic, my updater requests `https://api.adoptopenjdk.net/v3/assets/latest/11/hotspot`, parses the JSON and iterates through array of binaries. Once an item matches the criteria (https://github.com/tushev/aojdk-updatewatcher/blob/5e71a3164b60e7e7c759ec99c5bc9bfdddb9216e/src/Classes/Adoptium/AdoptiumAPI.cs#L140-L145), the updater stops looking for any other binaries and is happy with the first match (I expect that the API will provide most recent build).
<hr>

**If we are speaking about comparing versions in general** (say, you have  `"semver": "11.0.9+101"` installed locally), my updater will consider `"semver": "11.0.9+11"` as more recent, because `"build": 1` < `"build": 11`. Currently it relies on comparing standalone fields in sequence (`major>minor>security>build`) rather than parsing `semver`. Is this correct?

**Comment by OrangeDog** [comment]
@tushev 11.0.9+11 comes before 11.0.9+101, because 11 is less than 101.

**Comment by douph1** [comment]
>it is not present (at the time of writing this comment) in https://api.adoptopenjdk.net/v3/assets/latest/11/hotspot. I obtained the JSON both
Yes not present in /latest/ because of ordering issue we are currently trying to fix 

You can see it here /v3/assets/version/{version}

>Currently it relies on comparing standalone fields in sequence (major>minor>security>build)
Yes same problem here because Adopt and you handle only 3 field + build number before this new release.
and now 4 field + build number

If you sort with each uniq attribut yes 11.0.9+11 = 11.0.9.0.(+b)11 has a build=11 and 11.0.9+101 = 11.0.9.1.(+b)1 has a build=1 then your ordering failed
If you sort with semver you must be good because 11<101

**Comment by douph1** [comment]
see https://github.com/AdoptOpenJDK/TSC/issues/185#issuecomment-724696068

**Comment by tushev** [comment]
@douph1 @OrangeDog OK, I have to switch to `semver` for the API. That's one part of comparison.

As for the other part (local installation), I have:
* [Registry](https://github.com/tushev/aojdk-updatewatcher/blob/5e71a3164b60e7e7c759ec99c5bc9bfdddb9216e/src/Classes/Adoptium/AdoptiumInstallationsDiscoverer.cs#L36): `HKEY_LOCAL_MACHINE\SOFTWARE\AdoptOpenJDK\JRE\`**`11.0.7.10`**`\openj9\MSI`. Will that version reflect your recent changes?
* `SEMANTIC_VERSION="11.0.9+6"` in `release` file (see https://github.com/AdoptOpenJDK/openjdk-build/pull/2049) - I use for user-configured installations (actually for everything that is not auto-discovered via registry)
* legacy builds that do not have one or both sources. But it's simpler, because most likely they will have differences in `major/minor/security`, so `need_update` will still be `true` for them.

**Comment by douph1** [comment]
>Will that version reflect recent changes?

101 like in semver for the reg key

>1+1 visible in the installer name
>101 in the ProductVersion
>101 by default in the path "C:\Program Files\AdoptOpenJDK\jdk-11.0.9.101-hotspot\bin\javaw.exe" -jar "%1" %*
>101 in the registry HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\JDK\11.0.9.101

**Comment by douph1** [comment]
Please keep an eye on https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/313 and possible ongoing enhancement if you don't want to switch to semver comparaison

**Comment by tushev** [comment]
upd: what the updater is actually doing: it makes best effort to determine version of local installation. It is guaranteed that it can obtain `Major.Minor.Security`. If user enables use of windows registry for discovery (as well as for some recent builds - see `release` file) then it is possible to determine `Major.Minor.Security+Build` (all numbers are currently treated as integers). Then it compares the numbers with the API (`/latest/`).

**Please correct me if I'm wrong:** if I change my API logic so it uses semver like 11.0.9+`101` as a source for build number instead of dedicated `build` field, then this will be consistent with the other changes that are proposed in https://github.com/AdoptOpenJDK/TSC/issues/185#issuecomment-724696068 ?

From the point of view of updater, it will get then 101 > 11 and will show update dialog.

**Comment by tushev** [comment]
P.S. For legacy builds that are not auto-discovered via registry, it is not possible to get build number at all (if `build` is missing in `release`). These installations will not receive any updates unless `security` or greater field changes. This is a documented feature.

**Comment by douph1** [comment]
Yes it will be consistent and the only way "for now" as the "patch" information is not published into the api as a dedicated field : major.minor.security(.patch)+build  ( patch doesn't exists on the API )
Only semver include patch into : 4rd number : patch(*100)+build for the adopt semver version.

**Comment by douph1** [comment]
"build" cannot change without any other major/minor/sec/patch change

**Comment by tushev** [comment]
@douph1 will this numbering scheme remain in the future? 

It's OK for me to switch, just don't want to change the behavior very frequently...

**Comment by douph1** [comment]
I have no crystal ball :)
Don't be in a hurry to change now as AdoptOpenJDK/openjdk-api-v3#313 is not closed or be prepare to change one more time :)

**Comment by tushev** [comment]
OK, I will wait :) 

>101 by default in the path "C:\Program Files\AdoptOpenJDK\jdk-11.0.9.101-hotspot\bin\javaw.exe" -jar "%1" %*
101 in the registry HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\JDK\11.0.9.101

But since I will have to parse these as well and compare, I guess `semver` (or another field that reflects registry version) will be my best option

**Comment by tushev** [comment]
Just released https://github.com/tushev/aojdk-updatewatcher/releases/tag/2.0.1.0

@douph1 Now the updater should be able to see the latest version of `11` - `"openjdk_version": "11.0.9.1+1", "semver": "11.0.9+101"`. 

Currently I tried to implement the versioning to the best of my own understanding, still waiting to get confirmation/clarification from the official team on https://github.com/AdoptOpenJDK/openjdk-support/issues/209 :) So there may be more upcoming updates of the updater...

Also, I switched to WiX, now all the releases are provided as MSIs and ZIPs. No more false positives on VirusTotal caused by Inno Setup.

**Comment by RobFosterNYC** [comment]
16 was released.  I'm waiting for the Adopt team to have their gerbils wake up and update the website 😸

**Comment by maverick74** [comment]
@AdamBrousseau Hi,

You pushed a commit and referenced this issue.
Can you elaborate more about your push?

Could that work here as well?

**Comment by AdamBrousseau** [comment]
@maverick74 I believe that is unrelated. Likely a reference to `#4` of another fork.
