### ISSUE TITLE
Installer pipeline is now broken when all architectures is passed

### ISSUE THREAD

**Issue by gdams** [adoptium/installer#531]
Since https://github.com/adoptium/installer/commit/b7d100c6164d0b60a6cc3c3b39b5c059c7ae2559 was landed we have now broken the ability to build the Debian job for all architectures.

I've already fixed one issue via https://github.com/adoptium/installer/commit/3ea74367542f1c25d315d0e241d062ff8f788434 but the job will not automatically create several child jobs for each available Debian architecture which renders it useless.

As a workaround for now I'll run the Debian job for each architecture that we need individually.

**Comment by zdtsw** [comment]
is the problem/error from https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline_new/ or https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline?

**Comment by gdams** [comment]
with the _new pipeline

**Comment by zdtsw** [comment]
related to https://github.com/adoptium/installer/issues/459

**Comment by zdtsw** [comment]
think i finally understand the problem.

when we select "`all"` as ARCH it wont work for Debian,  because:
the label will be set to` "dockerBuild&&linux&&x64" ` which only works for x86_64 not the other ARCH

i will draft an PR to fix this one. 
for the time being it is best to run each ARCH per build (i.e not use `all`)

**Comment by zdtsw** [comment]
the build of deb "dpkg-buildpackage" does not really take in different ARCH, it only use the host arch to build package, this probably is the reason why we have to set label for the runs.
