### ISSUE TITLE
Add Eclipse Temurin packages for alpine repository to Repology

### ISSUE THREAD

**Issue by lfvjimisola** [adoptium/installer#588]
We use [renovate for version monitoring](https://docs.renovatebot.com/modules/datasource/#repology-datasource) and it works for standard apk packages. However, it does not work with Eclipse Temurin packages since the [alpine repository](https://packages.adoptium.net/ui/native/apk/alpine/main) is not available in [Repology](https://repology.org/).

Another option would be to use [GitHub releases API](https://github.com/adoptium/temurin17-binaries) but those version number to not match APK version number.

**Comment by lfvjimisola** [comment]
Any chance of this happening? Don't think that a non-project member can do this.

**Comment by karianna** [comment]
Doesn't sound like Repology has major market share so closing this as won't fix for now

**Comment by lfvkalle** [comment]
Renovate has a significant market share, and it uses repology as one of its sources. There really is no easy workaround that could solve this issue for us since neither [Dependabot](https://github.com/dependabot/dependabot-core/issues/2129) nor Renovate currently support managing external APK packages. Can you consider reopening this one @karianna?

**Comment by karianna** [comment]
@lfvkalle Can you point us to that data?

**Comment by lfvjimisola** [comment]
@karianna 

[Dependabot ](https://github.com/dependabot/dependabot-core(used a lot by GitHub projects): 3.6k stars
[Renovatebot](https://github.com/renovatebot/renovate): 13.6k
